apiVersion: apps/v1
kind: Deployment
metadata:
  name: user 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user 
    spec:
      containers:
      - image: user:latest
        name: user 
        ports:
        - containerPort: 8002

---

apiVersion: v1
kind: Service
metadata:
  name: user 
ports:
- port: 80
  protocol: TCP
  targetPort: 8002
spec:
  selector:
    app: user 
type: LoadBalancer
